---


################################################################################

- hosts:
    - all
  become: 'true'
  gather_facts: 'false'
  tasks:
    - name: Create variable from command line invocation fo Figlet
      command: "figlet -W -f standard '{{ use_hostname }}' -w 170"
      register: command_output
      failed_when: command_output is failed
      changed_when: 'false'
      tags:
        - host


    - name: Set variables for MOTD
      set_fact:
        common_message_motd: "{{ command_output.stdout }}"
        common_couleur_motd: "{{ host_specific_motd_color | default('33') }}"
      tags:
        - host


    - name: Create /etc/motd
      template:
        src: "motd.j2"
        dest: "/etc/motd"
        mode: "0755"
      changed_when: 'false'
      tags:
        - host
