---


################################################################################


- hosts:
    - all
  become: 'true'
  gather_facts: 'false'
  tasks:
    - name: Configure | hostname
      hostname:
        name: "{{ ansible_nodename }}"
      changed_when: 'false'
      tags:
        - host
        - commun
