---


################################################################################


# Certbot: génère ce qu'il faut pour HTTPS/SSL
- hosts:
    - all
  become: 'true'
  gather_facts: 'false'

  vars:
    certbot_admin_email: info@20100.net
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - "{{ sub_domain }}{{ domain_name }}.{{ tld }}"
    certbot_auto_renew_user: "{{ createur_linux_de_site | default(lookup('env', 'USER')) }}"
    certbot_create_command: >-
      "{{ certbot_script }} certonly --standalone --noninteractive --agree-tos
      --cert-name {{ sub_domain }}{{ domain_name }}.{{ tld }}
      --cert-path /etc/letsencrypt/live/{{ sub_domain }}{{ domain_name }}.{{ tld }}
      --email {{ cert_item.email | default(certbot_admin_email) }}
      -d {{ cert_item.domains | join(',') }}"

    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ sub_domain }}{{ domain_name }}.{{ tld }}" # "dev.nclsvncnt.net"
        root: "/mnt/disks/{{ instance_data_disk_name }}/nginx/{{ sub_domain }}{{ domain_name }}.{{ tld }}"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "certbot_{{ sub_domain }}{{ domain_name }}.{{ tld }}.conf"
        extra_parameters: |
          ssl_certificate     "/etc/letsencrypt/live/{{ sub_domain }}{{ domain_name }}.{{ tld }}/fullchain.pem;"
          ssl_certificate_key "/etc/letsencrypt/live/{{ sub_domain }}{{ domain_name }}.{{ tld }}/privkey.pem;"
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  pre_tasks:
    # - name: Update apt cache.
    #   apt: update_cache=true cache_valid_time=600
    #   when: ansible_os_family == 'Debian'
    #   changed_when: false

    - name: Install dependencies (RedHat).
      yum:
        name: "{{ item }}"
        state: present
      when:
        - ansible_os_family == 'RedHat'
      with_items:
        - cronie
        - epel-release

    - name: "installation et création du nécéssaire pour le site web"
      import_tasks: install-and-configure-fichiers-site-web.yaml

    - name: Install cron (Debian).
      apt:
        name: cron
        state: present
      when:
        - ansible_os_family == 'Debian'

  roles:
    - geerlingguy.certbot
  tags:
    - certbot
    - lestencrypt
