---


################################################################################
- hosts:
    - all
  become: 'true'
  gather_facts: 'false'
  vars_files: # 'Include environment specific "gcp_*" variables (zone, creds json etc.) infos'
      - "{{ playbook_dir }}/inventories/{{ infra_environment }}/inventory.compute.gcp.yaml"

  tasks:

    - name: "Create the required directory if it does not exist"
      file:
        path: /etc/google/auth/
        state: directory
        mode: '0700'
      tags:
        - logging
        - gcp

    # https://cloud.google.com/logging/docs/agent/authorization#copy-private-key
    # Required to permit access for monitoring/logging StackDriver agents
    - name: "Copy the agents's required permissions' file to the instance"
      copy:
        src: "{{ gcp_cred_file }}"
        dest: /etc/google/auth/application_default_credentials.json
        owner: root
        group: root
        mode: 0400
        backup: yes
      tags:
        - logging
        - gcp


    #see:
    # https://cloud.google.com/monitoring/workspaces/guide#single-project-ws
    # https://cloud.google.com/monitoring/agent/install-agent#linux-install
    - name: "Downloading logging agent"
      get_url:
        url: https://dl.google.com/cloudagents/install-logging-agent.sh
        dest: /tmp
        backup: 'true'
      tags:
        - logging
        - gcp


    - name: "Installing logging agent"
      command: bash install-logging-agent.sh
      args:
        chdir: /tmp
        creates: /sbin/google-fluentd
      tags:
        - logging
        - gcp
