---


################################################################################


# {{{ infOpen.fail2ban
- hosts:
    - all
  become: 'true'
  gather_facts: 'false'
  tasks:
    - name:
      package:
        name: iptables # necessaire au fonctionnement de fail2ban
        state: present
  roles:
    - role: infOpen.fail2ban
      state: absent
      tags:
        - fail2ban
      vars:
        fail2ban_service_name: 'fail2ban'
        fail2ban_jails: "{{ _fail2ban_jails | combine(mes_fail2ban_jails, recursive=true) }}"
        fail2ban_main_config_content: "{{ _fail2ban_main_config_content + mes_fail2ban_main_config_content }}"
        mes_fail2ban_main_config_content:
          - option: 'loglevel'
            value: 'INFO'
        fail2ban_filters:
          nginx-noscript:
            Definition:
              failregex: '^<HOST> -.*GET.*(\.asp|\.exe|\.pl|\.cgi|\.scgi)'
              ignoreregex: ''
          nginx-noproxy:
            Definition:
              failregex: '^<HOST> -.*GET http.*'
              ignoreregex: ''
        mes_fail2ban_jails:
          ssh:
            enabled: 'true'
            port: 'ssh'
            filter: 'sshd'
            logpath: '/var/log/auth.log'
            maxretry: 3
            bantime: 30m
            findtime: 5m
            ignoreip: '127.0.0.1/8  maison.vncnt.net'
          nginx-http-auth:
            enabled: 'true'
            filter: 'nginx-http-auth'
            port: 'http,https'
            logpath: '/var/log/nginx/error.log'
            ignoreip: '127.0.0.1/8  maison.vncnt.net'
          nginx-noscript: # source: https://www.digitalocean.com/community/tutorials/how-to-protect-an-nginx-server-with-fail2ban-on-ubuntu-14-04
            enabled: 'true'
            filter: 'nginx-noscript'
            port: 'http,https'
            logpath: '/var/log/nginx/access.log'
          nginx-badbots: # source: https://www.digitalocean.com/community/tutorials/how-to-protect-an-nginx-server-with-fail2ban-on-ubuntu-14-04
            enabled: 'true'
            filter: 'apache-badbots' # c'est voulu que ce soit Apache et pas nginx
            port: 'http,https'
            logpath: '/var/log/nginx/access.log'
            ignoreip: '127.0.0.1/8  maison.vncnt.net'
          nginx-noproxy: # source: https://www.digitalocean.com/community/tutorials/how-to-protect-an-nginx-server-with-fail2ban-on-ubuntu-14-04
            enabled: 'true'
            filter: 'nginx-noproxy'
            port: 'http,https'
            logpath: '/var/log/nginx/access.log'
            ignoreip: '127.0.0.1/8  maison.vncnt.net'
# }}}
