---


################################################################################
# this Play server the purpose of botstrapping nodes by installing
# python2, p4d etc. if it absent from the freshly spun node


- name: "Installation de python si absent"
  import_playbook: python_bootstrap.yaml


- name: "on extrait les 'faits' au sujet du serveur SSI ce n'est pas déjà fait"
  import_playbook: gather_facts.yaml


- name: "installation de Figlet, qui permet d'imprimer le no0m du serveur lors du login"
  import_playbook: install-and-configure-figlet.yaml


- name: "configuration du nom du serveur"
  import_playbook: configure-hostname.yaml


- name: "configuration de la bannière qui est affichée au login"
  import_playbook: configure-motd.yaml


- name: "installation de trucs/logiciels communs"
  import_playbook: trucs_communs.yaml
  tags:
    - never
    - logiciels


- name: "installation de Fail2ban qui permet de bannir les adresses IP de hackers qui essaient de se brancher de force sur notre serveur"
  import_playbook: install-and-configure-fail2ban.yaml


- name: "installation de l'agent Datadog qui permet de surveiller les ressources du serveur"
  import_playbook: install-and-configure-datadog.yaml

      # juste sur 03
# - name: "installation de l'agent Google de surveillance des ressources du serveur"
#   import_playbook: install-and-configure-monitoring-agent.yaml

      # juste sur 04
# - name: "installation de l'agent Google qui aggrège les logs du serveur"
#   import_playbook: install-and-configure-logging-agent.yaml


- name: "installation de Certbot qui permet de générer gratuitement des certificats SSL pour le HTTPS"
  import_playbook: install-and-configure-certbot.yaml


- name: "installation de Nginx, le serveur web lui même"
  import_playbook: install-and-configure-nginx.yaml



- hosts:
    - all
  gather_facts: 'false'
  tasks:
    - name:  "on config 'timezone => Canada/Eastern'"
      timezone:
        name: Canada/Eastern
      tags:
        - timezone

    - name: "on force un redémmarage car après env. 24h, on dirait que les f1-micro cessent de répondre..."
      cron:
        name: "on force un redémmarage car après env. 24h, on dirait que les f1-micro cessent de répondre..."
        minute: "37"
        hour: "1,13"
        job: "sudo reboot > /dev/null"
        user: "{{ createur_linux_de_site }}" # Adaoh ou Nicolas
        state: absent
      tags:
        - cronreboot

    - debug:
        msg: "Work is done on host: {{ ansible_host }}, distribution: {{ ansible_distribution }}, version: {{ ansible_distribution_version }}"
        # verbosity: 2
  tags:
    - always
