---


################################################################################


- hosts:
    - all
  become: 'true'
  gather_facts: 'false'

  tasks:
    - name: "Installing - start with epel-release for common for CENTOS"
      package:
        name: "{{ item }}"
        state: present
        update_cache: 'true'
      loop:
        - 'epel-release'
      loop_control:
        label: "  -  on installe: {{ item }}"
      when: ansible_distribution == "CentOS" or ansible_distribution == "Scientific"
      tags:
        - epel


    - name: "Installing - common no-configs software packages for CENTOS"
      package:
        name: "{{ item }}"
        state: present
        update_cache: 'true'
      loop:
        - 'net-tools'
      loop_control:
        label: "  -  on installe: {{ item }}"
      when: ansible_distribution == "CentOS" or ansible_distribution == "Scientific"


    - name: "Mise à jour de APT for UBUNTU"
      command: sudo apt-get update
      when: ansible_distribution == "Ubuntu"


    - name: "Installing - common no-configs software packages for UBUNTU"
      apt:
        name: "{{ item.logiciel }}"
        state: "{{ item.statut }}"
      loop:
        # - { statut: 'present', logiciel: 'mysql-server', commentaire: '' }
        - { statut: 'absent', logiciel: 'alien', commentaire: '' }
        - { statut: 'absent', logiciel: 'avahi-daemon', commentaire: '' }
        - { statut: 'absent', logiciel: 'avahi-utils', commentaire: '' }
        - { statut: 'absent', logiciel: 'dirmngr', commentaire: '' }
        - { statut: 'absent', logiciel: 'exfat-fuse', commentaire: '' }
        - { statut: 'absent', logiciel: 'firewalld', commentaire: '' }
        - { statut: 'absent', logiciel: 'landscape-common', commentaire: '' }
        - { statut: 'absent', logiciel: 'libnss-winbind', commentaire: '' }
        - { statut: 'absent', logiciel: 'libpam-cap', commentaire: '' }
        - { statut: 'absent', logiciel: 'libpam-winbind', commentaire: '' }
        - { statut: 'absent', logiciel: 'lm-sensors', commentaire: '' }
        - { statut: 'absent', logiciel: 'nbtscan', commentaire: '' }
        - { statut: 'absent', logiciel: 'net-tools', commentaire: '' }
        - { statut: 'absent', logiciel: 'nmap', commentaire: '' }
        - { statut: 'absent', logiciel: 'parallel', commentaire: '' }
        - { statut: 'absent', logiciel: 'pollinate', commentaire: '' }
        - { statut: 'absent', logiciel: 'python-apt', commentaire: '' }
        - { statut: 'absent', logiciel: 'selinux-utils', commentaire: '' }
        - { statut: 'absent', logiciel: 'speedometer', commentaire: 'network monitor' }
        - { statut: 'absent', logiciel: 'tcsh', commentaire: '' }
        - { statut: 'absent', logiciel: 'update-motd', commentaire: '' }
        - { statut: 'present', logiciel: 'apt-utils', commentaire: '' }
        - { statut: 'present', logiciel: 'bmon', commentaire: '' }
        - { statut: 'present', logiciel: 'git', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-cli', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-common', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-curl', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-dev', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-fpm', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-gd', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-imagick', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-imap', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-intl', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-mbstring', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-mysql', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-opcache', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-soap', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-xml', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-xmlrpc', commentaire: '' }
        - { statut: 'present', logiciel: 'php7.3-zip', commentaire: '' }
      loop_control:
        label: "  -  on (des)installe: {{ item.logiciel }}, utile pour: {{ item.commentaire }}"
      when: ansible_distribution == "Ubuntu"
      tags:
        - common
        - basic
        - ubuntu


    - name: "Installing - common no-configs software packages COMMON"
      package:
        name: "{{ item.logiciel }}"
        state: "{{ item.statut }}"
      loop:
        - { statut: 'absent', logiciel: 'ethtool', commentaire: '' }
        - { statut: 'absent', logiciel: 'iperf3', commentaire: '' }
        - { statut: 'absent', logiciel: 'mtr', commentaire: '' }
        - { statut: 'absent', logiciel: 'net-tools', commentaire: '' }
        - { statut: 'absent', logiciel: 'nethogs', commentaire: 'network monitor' }
        - { statut: 'absent', logiciel: 'nload', commentaire: 'network monitor' }
        - { statut: 'absent', logiciel: 'nodejs', commentaire: '' }
        - { statut: 'absent', logiciel: 'python3-virtualenv', commentaire: '' }
        - { statut: 'absent', logiciel: 'qperf', commentaire: '' }
        - { statut: 'absent', logiciel: 'reptyr', commentaire: '' }
        - { statut: 'absent', logiciel: 'screen', commentaire: '' }
        - { statut: 'absent', logiciel: 'tree', commentaire: '' }
        - { statut: 'absent', logiciel: 'certbot', commentaire: 'for LetsEncrypt certificates generation' }
        - { statut: 'absent', logiciel: 'colordiff', commentaire: '' }
        - { statut: 'present', logiciel: 'curl', commentaire: '' }
        - { statut: 'present', logiciel: 'fail2ban', commentaire: '' }
        - { statut: 'present', logiciel: 'git', commentaire: '' }
        - { statut: 'present', logiciel: 'htop', commentaire: '' }
        - { statut: 'present', logiciel: 'python-pip', commentaire: '' }
        - { statut: 'present', logiciel: 'python-setuptools', commentaire: '' }
        - { statut: 'present', logiciel: 'python3-pip', commentaire: '' }
        - { statut: 'present', logiciel: 'python3-setuptools', commentaire: '' }
        - { statut: 'present', logiciel: 'rsync', commentaire: '' }
        - { statut: 'present', logiciel: 'unzip', commentaire: '' }
        - { statut: 'present', logiciel: 'vim', commentaire: '' }
        - { statut: 'present', logiciel: 'wget', commentaire: '' }
      loop_control:
        label: "  -  on installe: {{ item.logiciel }}, utile pour: {{ item.commentaire }}"
      tags:
        - common
        - basic

    - name: "installation de bmon"
      raw: cd /tmp && rm -fr /tmp/bmon && git clone https://github.com/tgraf/bmon.git && cd bmon  &&  yum -y groupinstall 'Development Tools' &&  sudo yum -y install dh-autoreconf  make libconfuse-devel libnl3* ncurses-devel     && sudo ./autogen.sh && sudo ./configure && sudo make && sudo make install
      tags: bmon
      when: ansible_distribution == "CentOS" or ansible_distribution == "Scientific"

    - name: "install python's pexpect"
      debugger: on_failed
      pip:
        extra_args: '--upgrade'
        name: "{{ item.logiciel }}"
        state: "{{ item.statut }}"
      loop:
        - { statut: 'present', logiciel: 'setuptools', commentaire: 'dependances' }
        - { statut: 'present', logiciel: 'pexpect', commentaire: 'pour permettre de scripter des question/réponses pour certaines tâches' }
      tags:
        - common
        - basic
        - pexpect
